# Generated by Django 4.0.3 on 2022-04-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_profile_tracker_postfood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('ingredients', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
