# Generated by Django 4.0.3 on 2022-04-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0005_alter_menu_breakfast_alter_menu_dinner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_tracker',
            name='all_food_selected_today',
            field=models.ManyToManyField(related_name='inventory', through='meal.PostFood', to='meal.food'),
        ),
    ]
