# Generated by Django 4.0.3 on 2022-04-11 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal', '0006_profile_tracker_all_food_selected_today'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile_tracker',
            new_name='Meal_tracker',
        ),
    ]
