# Generated by Django 4.0.3 on 2022-04-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0007_rename_profile_tracker_meal_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
