# Generated by Django 4.0.3 on 2022-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0008_alter_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_tracker',
            name='calorie_goal',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
