# Generated by Django 4.0.3 on 2022-04-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0009_alter_meal_tracker_calorie_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_tracker',
            name='calorie_goal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
