# Generated by Django 4.0.3 on 2022-04-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0006_alter_authuser_username'),
        ('meal', '0010_alter_meal_tracker_calorie_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='person_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.profile'),
        ),
        migrations.AlterField(
            model_name='meal_tracker',
            name='person_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_user.profile'),
        ),
    ]
