# Generated by Django 4.0.3 on 2022-04-26 20:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0012_alter_food_person_of_alter_meal_tracker_person_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
