# Generated by Django 4.0.3 on 2022-05-30 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0013_alter_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meal_tracker',
            name='quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
