# Generated by Django 4.0.3 on 2022-05-30 16:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0014_alter_food_calorie_alter_meal_tracker_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle_group', models.CharField(choices=[('chest', 'chest'), ('back', 'back'), ('arms', 'arms'), ('abdominals', 'abdominals'), ('legs', 'legs'), ('shoulders', 'shoulders')], max_length=10)),
                ('sets', models.PositiveIntegerField(default=0)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
