# Generated by Django 4.0.3 on 2022-05-30 19:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0015_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='video'),
            preserve_default=False,
        ),
    ]
