# Generated by Django 4.0.3 on 2022-05-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0018_exercise_fifth_exercise_exercise_first_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('CHEST', 'CHEST'), ('BACK', 'BACK'), ('BICEPS', 'BICEPS'), ('TRICEPS', 'TRICEPS'), ('ABS', 'ABS'), ('LEGS', 'LEGS'), ('SHOULDERS', 'SHOULDERS')], max_length=10),
        ),
    ]
