# Generated by Django 4.0.3 on 2022-05-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0020_exercise_calories_burned_alter_menu_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Abs', 'Abs'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders')], max_length=10),
        ),
    ]
