# Generated by Django 4.0.3 on 2022-09-17 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0021_alter_exercise_muscle_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_tracker',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
