# Generated by Django 4.0.3 on 2022-09-18 19:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meal', '0022_alter_meal_tracker_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meal_tracker',
            new_name='Calorie_counter',
        ),
    ]
