# Generated by Django 4.0.3 on 2022-09-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0024_meal_tracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal_tracker',
            old_name='meal_tracker_products',
            new_name='products',
        ),
    ]
