# Generated by Django 4.0.3 on 2022-09-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0025_rename_meal_tracker_products_meal_tracker_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal_tracker',
            old_name='products',
            new_name='meal_tracker_products',
        ),
    ]
