# Generated by Django 4.0.3 on 2022-09-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0028_meal_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_tracker',
            name='person_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meal.calorie_counter'),
        ),
    ]
