# Generated by Django 4.0.3 on 2022-09-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0030_meal_tracker_quantity_alter_meal_tracker_person_of'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meal_tracker',
        ),
    ]
