# Generated by Django 4.0.3 on 2022-10-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0031_delete_meal_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity_units',
            field=models.CharField(choices=[('(gr)', '(gr)'), ('(kg)', '(kg)'), ('(l)', '(l)'), ('(ml)', '(ml)')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
