# Generated by Django 4.0.3 on 2022-10-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0032_food_quantity_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='quantity_units',
            field=models.CharField(choices=[('(gr)', '(gr)'), ('(kg)', '(kg)'), ('(l)', '(l)'), ('(ml)', '(ml)'), ('(n)', '(n)')], max_length=10),
        ),
    ]
