# Generated by Django 4.0.3 on 2022-10-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0033_alter_food_quantity_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='available_quantity',
            field=models.BooleanField(default=True),
        ),
    ]
