# Generated by Django 4.0.3 on 2022-10-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0034_food_available_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='calorie_counter',
            name='quantity_is_less',
            field=models.BooleanField(default=False),
        ),
    ]
