# Generated by Django 4.0.3 on 2022-11-13 13:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0036_alter_food_quantity_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie_counter',
            name='quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
