# Generated by Django 4.0.3 on 2022-11-13 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0037_alter_calorie_counter_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie_counter',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
