# Generated by Django 4.0.3 on 2022-11-22 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0038_alter_calorie_counter_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calorie_counter',
            name='quantity_is_less',
        ),
        migrations.AlterField(
            model_name='calorie_counter',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
