# Generated by Django 4.0.3 on 2022-04-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_alter_authuser_first_name_alter_authuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
